name = "SatResample"
uuid = "da75141d-1d2f-4a17-836c-db3d8e986037"
authors = ["Marcus Huntemann <marcus.huntemann@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
